workflows:
  ios-capacitor-build:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      vars:
        APP_NAME: "Stellar Guardian"
        BUNDLE_ID: "com.lucad.stellarguardian"   # Cambia con il tuo bundle id
        NODE_VERSION: "16"
      node: $NODE_VERSION
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Copy Capacitor assets
        script: |
          npx cap copy ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive
    publishing:
      email:
        recipients:
          - "rosangela.calasso69@gmail.com"   