workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      node: 20
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Setup iOS project
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install
      - name: Clean build folder
        script: |
          cd ios/App
          rm -rf ~/Library/Developer/Xcode/DerivedData
          xcodebuild clean -project App.xcodeproj -scheme App
      - name: Build iOS App for Simulator
        script: |
          cd ios/App
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -arch x86_64 \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            -derivedDataPath build
    artifacts:
      - ios/App/build/Build/Products/**/*.app
      - ios/App/build/Build/Products/**/*.dSYM