workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      node: 20
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Setup iOS project
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install
      - name: Build iOS
        script: |
          xcodebuild build -workspace ios/App/App.xcworkspace -scheme App -configuration Release -derivedDataPath build/ios
    artifacts:
      - build/ios/**/*.app