workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      node: 20
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Setup iOS project
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install
      - name: Build for device
        script: |
          cd ios/App
          # Crea l'archive per dispositivo reale
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO
      - name: Create IPA
        script: |
          cd ios/App
          # Crea il file .ipa
          mkdir -p build/Payload
          cp -R build/App.xcarchive/Products/Applications/App.app build/Payload/
          cd build
          zip -r StellarGuardian.ipa Payload
          echo "✅ IPA created successfully!"
    artifacts:
      - ios/App/build/*.ipa