workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      node: 20
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Setup iOS project
        script: |
          npx cap sync ios
      - name: Fix Swift issues
        script: |
          cd ios/App
          # Rimuovi file problematici generati
          find . -name "GeneratedAssetSymbols.swift" -delete
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod deintegrate
          pod install --repo-update
      - name: Build iOS project
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_SUPPRESS_WARNINGS=YES \
            -quiet
    artifacts:
      - ios/App/build/**