workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      node: 20
      xcode: 14.3
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Setup iOS project
        script: |
          npx cap sync ios
      - name: Update iOS deployment target
        script: |
          cd ios/App
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [^;]*/IPHONEOS_DEPLOYMENT_TARGET = 13.0/' App.xcodeproj/project.pbxproj
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod deintegrate
          pod install --repo-update
      - name: Build iOS Archive
        script: |
          cd ios/App
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/App.xcarchive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            -allowProvisioningUpdates \
            | xcpretty
    artifacts:
      - ios/App/build/**